# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::518370722418:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8YWZU36ZGVCO
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::518370722418:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-17T06:11:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1576"
  uid: 8c7661f2-032d-423e-b6a2-9335ecd08a01
